export const FETCH_LAYOUT_DATA = "FETCH_LAYOUT_DATA";
export const MODIFY_LAYOUT = "MODIFY_LAYOUT";
export const FETCH_MAIN_CONTENT_DATA = "FETCH_MAIN_CONTENT_DATA";
export const FETCH_MOVIES_FROM_URL = "FETCH_MOVIES_FROM_URL";
export const UPDATE_MOVIE_LIST = "UPDATE_MOVIE_LIST";
